- group:
    name: dev
- user:
    name: dev
    group: rideflow
    shell: /bin/bash
    comment: "RideFlow developer"
- name: link app directory into user directory
  file:
    src: /rideflow
    dest: /home/dev/rideflow
    state: link
    owner: dev
    group: dev
