# remember to set these ip to name mappings in your /etc/hosts file
# if you are developing on a local virtual machine:
nginx:
    vend: 
        ip: 172.28.128.3
        name: vendapi.ourtransit.com
        port: 80
    ride:
        ip: 172.28.128.3
        name: rideapi.ourtransit.com
        port: 80
    manage:
        ip: 172.28.128.3
        name: manage.ourtransit.com
        port: 80
    public:
        ip: 172.28.128.3
        name: api.ourtransit.com
        port: 443
db:
    dsn: dbi:Pg:dbname=rideflow;host=localhost
    user: rideflow
    password: rideflow

ht:
    public:
        listen:
            - 'http://127.0.0.1:8080'
        proxy: 1
    ride:
        listen:
            - 'http://127.0.0.1:8070'
        proxy: 1
    vend:
        listen:
            - 'http://127.0.0.1:8060'
        proxy: 1
    manage:
        listen:
            - 'http://127.0.0.1:8050'
        proxy: 1
