---
rider_class:
    description: enumeration for different kinds of riders
    type: string
    enum:
        - General
        - Adult
        - Youth
        - Senior
payment_class:
    description: how rides and passes have been paid for
    type: string
    enum:
        - Cash
        - Debit
        - Credit
        - Promotion
        - Complimentary
location:
    description: a latitude/longitude pair
    type: array
    format: point
    minItems: 2
    maxItems: 2
    items:
      type: number
Identifiable:
    description: role for things with a uuid
    type: object
    x-dbic-key: id
    properties:
      id:
          type:   string
          format: uuid
          x-rideflow-scope: public
Archivable:
    description: role for things that shouldn't be deleted
    type: object
    properties:
      archived:
          type:   boolean
          x-rideflow-scope: protected
Locatable:
    description: role for things that have a position in space
    allOf:
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              location:
                  $ref: '#/definitions/location'
                  x-rideflow-scope: public
Vectorable:
    description: role for things with position and direction
    allOf:
        - $ref: '#/definitions/Locatable'
        - type: object
          properties:
              bearing:
                  description: bearing (in degrees) clockwise from true North
                  type: number
              heading:
                  description: textual description of direction
                  x-rideflow-scope: public
                  x-dbic-ignore: true
                  type: string
                  enum:
                      - North
                      - NorthEast
                      - East
                      - SouthEast
                      - South
                      - SouthWest
                      - West
                      - NorthWest
Updateable:
    description: role for things whose status are regularly updated
    allOf:
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              date_updated:
                  x-rideflow-scope: protected
                  type: string
                  format: date-time
Pass:
    description: a credit for riding the transit system
    x-rideflow-scope: protected
    x-dbic-table: passes
    allOf:
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              date_issued:
                  type:   string
                  format: date-time
                  description: Date Purchased/Created
              rides:
                  type: integer
                  format: int32
                  description: Rides remaining
              rides_remaining:
                  type: integer
                  format: int32
                  description: Rides remaining
              class:
                  $ref: '#/definitions/rider_class'
              duration:
                  type: integer
                  format: int32
                  description: Value of pass
              duration_type:
                  type: string
                  description: units 'duration' is measured in
                  enum:
                      - hours
                      - days
                      - weeks
                      - months
              date_expires:
                  type:   string
                  format: date-time
                  description: Last day pass is valid
              guest_id:
                  type: string
                  description: Identifier for partner program
PassGroup:
    description: a set of passes maintained by a smart device (so a family could board with a single swipe, for example)
    allOf:
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              passes:
                  type: array
                  items:
                      $ref: '#/definitions/Pass'
Route:
    description: A set of stops
    x-dbic-table: routes
    x-rideflow-scope: public
    allOf:
        - $ref: '#/definitions/Identifiable'
        - $ref: '#/definitions/Archivable'
        - type: object
          properties:
              name:
                  type: string
              path:
                  description: a set of ordered coordinates describing the route
                  type: array
                  items:
                    $ref: '#/definitions/location'
              color:
                  type: string
                  enum:
                    - Red
                    - Green
                    - Blue
                    - Orange
                    - Yellow
                    - Purple
                    - Pink
                    - Silver
                    - Gold
                    - Gray
                    - Black
              stops:
                  type: array
                  x-dbic-rel: many_to_many
                  x-dbic-them: stop
                  x-dbic-bridge-name: route_stops
                  x-dbic-bridge-indexed: true
                  x-dbic-key: route_id
                  x-dbic-bridge: '#/definitions/RouteStop'
                  items:
                      $ref: '#/definitions/Stop'
Stop:
    description: A transit stop
    x-dbic-table: stops
    x-rideflow-scope: public
    allOf:
        - $ref: '#/definitions/Archivable'
        - $ref: '#/definitions/Locatable'
        - $ref: '#/definitions/Updateable'
        - type: object
          properties:
              name:
                  type: string
              arrival:
                  x-dbic-ignore: true
                  $ref: '#/definitions/Arrival'
              routes:
                  type: array
                  readOnly: true
                  x-dbic-rel: many_to_many
                  x-dbic-them: route
                  x-dbic-bridge-name: route_stops
                  x-dbic-key: stop_id
                  x-dbic-bridge: '#/definitions/RouteStop'
                  items:
                    $ref: '#/definitions/Route'
Arrival:
    description: Information about the next vehicle arriving at this stop
    type: object
    x-rideflow-scope: public
    properties:
        name:
            description: description of the vehicle arriving
            type: string
        minutes:
            description: number of minutes until the next vehicle arrives
            type: integer
RouteStop:
    description: many to many bridge for Routes and Stops
    x-scope: dbic
    x-dbic-table: route_stops
    x-dbic-key:
        - stop_id
        - route_id
    type: object
    properties:
        stop:
            x-dbic-rel: belongs_to
            x-dbic-key: stop_id
            $ref: '#/definitions/Stop'
        route:
            x-dbic-rel: belongs_to
            x-dbic-key: route_id
            $ref: '#/definitions/Route'
        index:
            type: integer
RouteSession:
    description: A period of time when a vehicle is actively plying a route
    x-rideflow-scope: protected
    x-dbic-table: route_sessions
    allOf:
      - $ref: '#/definitions/Archivable'
      - $ref: '#/definitions/Vectorable'
      - $ref: '#/definitions/Updateable'
      - type: object
        properties:
            session_start:
                type: string
                format: date-time
            session_end:
                type: string
                format: date-time
            route:
                x-dbic-rel: belongs_to
                x-dbic-key: route_id
                $ref: '#/definitions/Route'
            vehicle:
                x-dbic-rel: belongs_to
                x-dbic-key: vehicle_id
                $ref: '#/definitions/Vehicle'
            driver:
                x-dbic-rel: belongs_to
                x-dbic-key: driver_id
                $ref: '#/definitions/User'
            rides:
                type: array
                x-dbic-rel: has_many
                x-dbic-key: route_session_id
                items:
                    $ref: '#/definitions/Ride'
Ride:
    description: a logged ride on the transit system
    x-dbic-table: rides
    x-rideflow-scope: protected
    allOf:
      - $ref: '#/definitions/Archivable'
      - $ref: '#/definitions/Vectorable'
      - type: object
        properties:
            timestamp:
                type: string
                format: date-time
            token:
                x-rideflow-scope: private
                x-dbic-rel: belongs_to
                x-dbic-key: token_id
                $ref: '#/definitions/Pass'
            route_session:
                x-rideflow-scope: private
                x-dbic-rel: belongs_to
                x-dbic-key: route_session_id
                $ref: '#/definitions/RouteSession'
            pass_type:
                type: string
                enum:
                    - Token
                    - Pass
                    - Mobile
            class:
                $ref: '#/definitions/rider_class'
Vendor:
    description: a machine or business that sells tokens and passes
    x-dbic-table: vendors
    x-rideflow-scope: public
    allOf:
        - $ref: '#/definitions/Archivable'
        - $ref: '#/definitions/Locatable'
        - type: object
          properties:
              name:
                  type: string
User:
    description: an employee of the transit system
    x-rideflow-scope: protected
    x-dbic-table: users
    allOf:
        - $ref: '#/definitions/Archivable'
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              firstname:
                  type: string
              lastname:
                  type: string
              email:
                  type: string
                  format: email
                  x-scope: internal
                  x-unique: true
              password:
                  type: string
                  format: password
                  x-scope: internal
              salt:
                  type: string
                  x-scope: internal
              roles:
                  type: array
                  items:
                      type: string
                      enum:
                          - Driver
                          - Manager
PasswordReset:
    description: a temporary token to allow a user to reset their password
    x-rideflow-scope: protected
    x-dbic-table: password_reset
    allOf:
        - $ref: '#/definitions/Identifiable'
        - type: object
          properties:
              expires:
                  type: string
                  format: date-time
              user:
                  x-dbic-rel: belongs_to
                  x-dbic-key: user_id
                  $ref: '#/definitions/User'
Vehicle:
    description: a vehicle plys a route to transport riders
    x-dbic-table: vehicles
    x-rideflow-scope: protected
    allOf:
        - $ref: '#/definitions/Identifiable'
        - $ref: '#/definitions/Archivable'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
              description: vehicle Identifier
            type:
              type: string
              enum:
                  - Bus
                  - Ferry
                  - Train
            notes:
                type: string
            sessions:
                x-dbic-rel: has_many
                x-dbic-key: vehicle_id
                type: array
                items:
                    $ref: '#/definitions/RouteSession'

