---
- name: install ntp
  apt:
    name: ntp
    update_cache: yes
- file:
    path: /rideflow/var/config
    state: directory
    mode: 0755
- group: 
    name: rideflow
    gid: 300
- user:
    name: rideflow
    group: rideflow
    uid: 300
    comment: "RideFlow app user"
