---
- copy:
    src: ../cpanfile
    dest: /root/cpanfile
    owner: root
    group: root
    mode: '0644'

- name:  Install cpanm
  shell: curl -L http://cpanmin.us | perl - App::cpanminus

- name: install uuid dependency
  apt:
    name: uuid-dev
    update_cache: yes

- name: install perl dependencies
  environment:
    PERL_MM_USE_DEFAULT: 1
  command: cpanm --installdeps /root/

- name: set up PERL5LIB
  shell: 'echo "\nexport PERL5LIB=/rideflow/lib:/rideflow/var/lib\n" >> /home/dev/.profile'

- name: set up server mode (MOJO_MODE)
  shell: 'echo "\nexport PLACK_ENV=development\n" >> /home/dev/.profile'

- name: set up server mode (PLACK_ENV)
  shell: 'echo "\nexport MOJO_MODE=development\n" >> /home/dev/.profile'
