---
- copy:
    src: ../cpanfile
    dest: /root/cpanfile
    owner: root
    group: root
    mode: '0644'

- name:  Install cpanm
  shell: curl -L http://cpanmin.us | perl - App::cpanminus

- name: install perl dependencies
  environment:
    PERL_MM_USE_DEFAULT: 1
  command: cpanm --installdeps /root/