---
- name: install nginx
  apt:
    name: nginx
    update_cache: yes

- file:
    path: /rideflow/var/static
    state: directory
    mode: 0755

- file:
    path: /rideflow/var/config/nginx
    state: directory
    mode: 0755

- name: remove static sites-available directory
  file:
    path: /etc/nginx/sites-available
    state: absent

- name: remove static sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: absent

- name: link nginx conf files
  file:
    src: /rideflow/var/config/nginx
    dest: /etc/nginx/sites-available
    state: link
    owner: rideflow
    group: rideflow

- name: enable all sites-available
  file:
    src: /etc/nginx/sites-available
    dest: /etc/nginx/sites-enabled
    state: link
    owner: rideflow
    group: rideflow

- name: 'add nginx user to rideflow group'
  user:
    name: data-www
    groups: rideflow
    append: yes

- name: configure nginx to start on boot
  service:
    name: nginx
    enabled: yes

- name: start nginx
  service:
    name: nginx
    state: started