---
- name: install nginx
  apt:
    name: nginx
    update_cache: yes

- file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0700

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Monmouth/O=RideFlow/CN=*.ourtransit.com" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt

- file:
    path: /rideflow/var/static
    state: directory
    mode: 0755

- file:
    path: /rideflow/var/config/nginx
    state: directory
    mode: 0755

- name: remove static sites-available directory
  file:
    path: /etc/nginx/sites-available
    state: absent

- name: remove static sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: absent

- name: link nginx conf file
  file:
    src: /rideflow/config/nginx_global.conf
    dest: /etc/nginx/conf.d/rideflow.conf
    state: link
    owner: rideflow
    group: rideflow

- name: link nginx site files
  file:
    src: /rideflow/var/config/nginx
    dest: /etc/nginx/sites-available
    state: link
    owner: rideflow
    group: rideflow

- name: enable all sites-available
  file:
    src: /etc/nginx/sites-available
    dest: /etc/nginx/sites-enabled
    state: link
    owner: rideflow
    group: rideflow

- name: 'add nginx user to rideflow group'
  user:
    name: data-www
    groups: rideflow
    append: yes

- name: configure nginx to start on boot
  service:
    name: nginx
    enabled: yes

- name: start nginx
  service:
    name: nginx
    state: started