---
- hosts: all
  vars:
    postgresql_dev_headers: yes
    postgresql_authentication:
      - type: local
        user: rideflow
        method: trust
  become: true
  become_user: root
  roles:
    - app
    - developer
    - ansible-postgresql
    - perl
    - nginx
- hosts: all
  become: true
  become_user: postgres
  roles:
    - postgres

    

