---
- hosts: all
  vars:
  become: true
  become_user: root
  roles:
    - perl
    - ansible-postgresql
  tasks:
    - file:
        path: /rideflow/var/config
        state: directory
        mode: 0755
    - group: 
        name: rideflow
    - user:
        name: rideflow
        group: rideflow
        comment: "RideFlow app user"
    - user:
        name: dev
        group: rideflow
        shell: /bin/bash
        comment: "RideFlow developer"
    - name: link app directory into user directory
      file:
        src: /rideflow
        dest: /home/dev/rideflow
        state: link
        owner: dev
        group: rideflow
- hosts: all
  become: true
  become_user: postgres
  roles:
    - postgres

    

