Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-8.2"

  synced_folder = "/host"
  synced_web_folder = "/host-web"
  hostname      = "rfmaster"

  config.vm.network "private_network", ip: "172.28.128.3"

  config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.provider "virtualbox" do |vb|
          vb.name   = "RideFlow Server"
          vb.memory = 4096
          vb.cpus   = 2
      end

      node.vm.synced_folder "../../", synced_folder,
          id: "app",
          mount_options: ["uid=300,gid=300,dmode=775,fmode=664"]

      node.vm.synced_folder "../../../rideflow-manager", synced_web_folder,
          id: "web",
          mount_options: ["uid=300,gid=300,dmode=775,fmode=664"]

      config.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get -y upgrade libssl1.0.0 openssl # forces an upgrade of libssl and openssl
      SHELL

      node.vm.provision "shell" do |shell|
          shell.name   = "set symlink to code base"
          shell.inline = "ln -sf /host /rideflow"
      end

      node.vm.provision "ansible" do |ansible|
          ansible.playbook = "../../ansible/playbook.yaml"
      end

  end


end
