Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-8.2"

  synced_folder = "/host"
  hostname      = "rfmaster"


  config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.provider "virtualbox" do |vb|
          vb.name   = "RideFlow Server"
          vb.memory = 4096
          vb.cpus   = 2
      end

      node.vm.synced_folder "../../", synced_folder

      node.vm.provision "ansible" do |ansible|
          ansible.playbook = "../../ansible/playbook.yaml"
      end
  end


end
